openapi: 3.0.0
info:
  title: API de Agendamento - Salão de Beleza
  description: API para agendamento de horários e serviços em salão de beleza.
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /agendamentos:
    post:
      summary: Realiza um novo agendamento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                telefone:
                  type: string
                data:
                  type: string
                  format: date
                horario:
                  type: string
                tipoDeServico:
                  type: string
              required:
                - nome
                - telefone
                - data
                - horario
                - tipoDeServico
      responses:
        '201':
          description: Agendamento realizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Agendamento'
        '400':
          description: Erro de validação
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
components:
  schemas:
    Agendamento:
      type: object
      properties:
        nome:
          type: string
        telefone:
          type: string
        data:
          type: string
        horario:
          type: string
        tipoDeServico:
          type: string
